export const COUNTRY_ALIASES: Record<string, string[]> = {
  US: ['USA', 'U.S', 'U.S.', 'AMERICA', 'STANY ZJEDNOCZONE', 'STANY', 'AMERYKA', 'UNITEDSTATES'],
  GB: ['UK', 'U.K', 'U.K.', 'GREAT BRITAIN', 'ENGLAND', 'WIELKA BRYTANIA', 'ANGLIA', 'BRITAIN'],
  PL: ['POLSKA'],
  DE: ['NIEMCY', 'BUNDESREPUBLIK DEUTSCHLAND', 'GERMANY'],
  AE: ['UAE', 'U.A.E', 'U.A.E.', 'ZJEDNOCZONE EMIRATY ARABSKIE', 'EMIRATY'],
  KR: ['SOUTHKOREA', 'KOREASOUTH', 'KOREA POŁUDNIOWA', 'KOREA'],
  CZ: ['CZECHIA', 'CZECH', 'CZECHY'],
}